# # # # # # # # # #
#   Marshall Lab  #
# # # # # # # # # #

# Basic
name:               "Marshall Echem Lab"
title:              "Marshall Electrochemical Engineering Lab at the University of Canterbury"
description:        "The Marshall Lab is an electrochemical engineering research group at the University of Canterbury, Christchurch, New Zealand."


# URL
url:                https://marshall-echem-lab.github.io
baseurl:            
#baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "news"
    href:           "/news"
  - name:           "resources"
    href:           "/resources"
    dropdown:
      - name:       "protocols"
        href:       "/resources/protocols"
      - name:       "software"
        href:       "/resources/software"
      - name:       "datasets"
        href:       "/resources/datasets"
  - name:           "join us"
    href:           "/join"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      permalink:    /:year/:month/:day/:title.html
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
